### ISSUE TITLE
Possible to keybind?

### ISSUE THREAD

**Issue by qwqwrqwqrw** [InfernoStats/SetTimer#2]
Would it be possible to add a custom keybind option to start / pause the timer. It would still be fully manual, but easier to use while in the inferno

**Comment by nbulischeck** [comment]
@qwqwrqwqrw Yes it's definitely possible. I'll add this in the next update later tonight. 1.1.0 just got merged to the plugin hub earlier so it might be a couple days before 1.2.0 (this feature) gets merged.

**Comment by InfernoStats** [comment]
https://github.com/InfernoStats/SetTimer/commit/a784672459d11a35578dabfe80d239c4f142c833 commit resolves this issue.

**Comment by InfernoStats** [comment]
This request has now been merged to the plugin-hub.

**Comment by qwqwrqwqrw** [comment]
Awesome work, thanks a lot for adding this. Very easy to use now

**Comment by nbulischeck** [comment]
@qwqwrqwqrw I agree. It made it a lot easier to start/stop in the moment. Thank you for your awesome suggestion 👍
