### ISSUE TITLE
fyi `doClick` contains a thread.sleep call, use doClick(0).

### ISSUE THREAD

**Issue by geheur** [InfernoStats/SetTimer#4]
or better yet, just run the code attached to the button handler directly.

Not sure if this affects anything but sleeping is probably not great in general.

**Comment by InfernoStats** [comment]
Just got a user report that the client lags if you press the hotkey button and holding the hotkey completely freezes the client so it looks like it definitely needs to be changed

**Comment by InfernoStats** [comment]
Should be resolved with 6acbb80170f347c8de0857c12410288f1020dd67
